# kubernetes/postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_HOST: ZXhhbXBsZQ==
  POSTGRES_PORT: ZXhhbXBsZQ==
  POSTGRES_USER: ZXhhbXBsZQ==
  POSTGRES_PASSWORD: ZXhhbXBsZQ==
  PGSSLMODE: cmVxdWlyZQ==
